{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-stale-cleanup.secretName" . }}
  labels:
    {{- include "keycloak-stale-cleanup.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keycloak.existingSecretKey }}: {{ .Values.keycloak.clientSecret | quote }}
{{- end }}
